### ISSUE TITLE
Nit: Consider Renaming Classes

### ISSUE THREAD

**Issue by Keepingshtum** [Trilinear/CS151-Uptick#3]
It's not immediately obvious that "Posts" and "Comments" are actually handlers to help with post and comment CRUD actions - may I suggest using something like PostService or PostHandler instead? 

Diagrams look good!

(If you're wondering what a nit is, [here's a cool link](https://josipmisko.com/posts/code-review-nit).)

You may proceed to implementation without addressing this issue since it is just a nit. Whichever you choose, leave a response below and close the issue once it is addressed.

**Comment by smntxz** [comment]
For now, I think it's fine to leave the diagram names as Post and Comments, but later down the line we will likely need to change the names when we add more functionality to clarify. When we add more diagrams for phase 2 we'll likely come back to this nit to fix it.
